export const IMAGES = {
  logo: "/images/logo.png",
  banner: "/images/banner.JPG",
  girl: "/images/girl.png",
  boy: "/images/boy.png",
  customers: "/images/customers.png",
  bag: "/images/bag.JPG",
  bee: "/images/bee.JPG",
  bra: "/images/bra.JPG",
  keychain: "/images/keychain.JPG",
  koala: "/images/koala.JPG",
  koala1: "/images/koala1.JPG",
  koala2: "/images/koala2.JPG",
  koala3: "/images/koala3.JPG",
  koala4: "/images/koala4.JPG",
  review: "/images/review.JPG",
  shrug: "/images/shrug.JPG",
  sweater: "/images/sweater.JPG",
  cats: "/images/cats.png",
  google: "/images/google.png",
};
